const mongoose = require("mongoose");
const { Property } = require("../../models");
const { upsertByUnique } = require("./helpers");
const { IDS } = require("./users");

// Absolute image URLs so both frontends render them via resolveImage()
// without needing a base URL prefix. Unsplash is used as placeholder art.
const IMG = {
  house1: [
    "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800",
    "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800",
    "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
  ],
  house2: [
    "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
    "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800",
  ],
  apartment: [
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
  ],
  condo: [
    "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
  ],
  land: [
    "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
  ],
  commercial: [
    "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800",
    "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800",
  ],
};

const propertiesData = [
  {
    createdBy: IDS.agent,
    title: "Modern Family Home in Gulshan",
    description:
      "A beautiful 4-bedroom family home with a spacious garden, modern kitchen, and a private garage in the heart of Gulshan.",
    catagory: "House",
    type: "Buy",
    address: "House 12, Road 5, Gulshan 2",
    city: "Dhaka",
    state: "Dhaka Division",
    zipCode: "1212",
    country: "Bangladesh",
    location: {
      type: "Point",
      coordinates: [90.4125, 23.7805],
    },
    mapLink: "https://maps.google.com/?q=Gulshan+2,Dhaka",
    price: 75000000,
    areaSqFt: 4200,
    lotSize: 0.5,
    yearBuilt: 2019,
    bedrooms: 4,
    bathrooms: 4,
    kitchen: 1,
    garage: 2,
    images: IMG.house1,
    status: "Available",
    features: ["Modern Kitchen", "Walk-in Closet", "Balcony"],
    amenities: ["Security", "Garden", "Parking"],
    isFeatures: true,
    isBosted: true,
    bostedRank: 1,
    views: 120,
    favorites: 15,
    inquiries: 5,
    commission: { percentage: 5, amount: 3750000, status: "pending" },
  },
  {
    createdBy: IDS.agent,
    title: "Cozy Apartment Near Dhanmondi Lake",
    description:
      "Well-maintained 3-bedroom apartment close to Dhanmondi Lake with easy access to schools and markets.",
    catagory: "Apartment",
    type: "Rent",
    address: "Flat 4A, Road 9, Dhanmondi",
    city: "Dhaka",
    state: "Dhaka Division",
    zipCode: "1205",
    country: "Bangladesh",
    location: {
      type: "Point",
      coordinates: [90.3744, 23.7461],
    },
    mapLink: "https://maps.google.com/?q=Dhanmondi+Lake,Dhaka",
    price: 45000,
    areaSqFt: 1650,
    yearBuilt: 2016,
    bedrooms: 3,
    bathrooms: 3,
    kitchen: 1,
    garage: 1,
    images: IMG.apartment,
    status: "Available",
    features: ["Lake View", "Lift"],
    amenities: ["Security", "Generator"],
    isFeatures: true,
    isBosted: false,
    views: 80,
    favorites: 9,
    commission: { percentage: 0, amount: 0, status: "waived" },
  },
  {
    createdBy: IDS.agent,
    title: "Luxury Condo in Banani",
    description:
      "High-floor luxury condo with panoramic city views, gym, pool, and 24/7 security in Banani.",
    catagory: "Condo",
    type: "Buy",
    address: "Condo 21, Road 11, Banani",
    city: "Dhaka",
    state: "Dhaka Division",
    zipCode: "1213",
    country: "Bangladesh",
    location: {
      type: "Point",
      coordinates: [90.4066, 23.7936],
    },
    price: 98000000,
    areaSqFt: 3100,
    yearBuilt: 2021,
    bedrooms: 4,
    bathrooms: 5,
    kitchen: 1,
    garage: 2,
    images: IMG.condo,
    status: "Available",
    features: ["Swimming Pool", "Gym", "City View"],
    amenities: ["Gym", "Pool", "Security", "Parking"],
    isFeatures: true,
    isBosted: true,
    bostedRank: 2,
    views: 210,
    favorites: 27,
    inquiries: 8,
    commission: { percentage: 5, amount: 4900000, status: "pending" },
  },
  {
    createdBy: IDS.agent,
    title: "Agricultural Land in Savar",
    description:
      "Prime agricultural land with road access, suitable for farming or future development near Savar.",
    catagory: "Land",
    type: "Buy",
    address: "Village Road, Savar",
    city: "Savar",
    state: "Dhaka Division",
    zipCode: "1340",
    country: "Bangladesh",
    location: {
      type: "Point",
      coordinates: [90.2567, 23.8583],
    },
    price: 35000000,
    areaSqFt: 43560,
    lotSize: 1,
    images: IMG.land,
    status: "Available",
    features: ["Road Access"],
    amenities: [],
    isFeatures: false,
    isBosted: false,
    views: 45,
    commission: { percentage: 3, amount: 1050000, status: "pending" },
  },
  {
    createdBy: IDS.agent,
    title: "Office Space in Motijheel",
    description:
      "Commercial office space in the financial district, ideal for corporate headquarters.",
    catagory: "Commercial",
    type: "Lease",
    address: "Level 7, Motijheel C/A",
    city: "Dhaka",
    state: "Dhaka Division",
    zipCode: "1000",
    country: "Bangladesh",
    location: {
      type: "Point",
      coordinates: [90.4178, 23.733],
    },
    price: 120000,
    areaSqFt: 2500,
    yearBuilt: 2012,
    images: IMG.commercial,
    status: "Rented",
    features: ["Meeting Rooms", "Lift"],
    amenities: ["Security", "Parking", "Generator"],
    isFeatures: false,
    isBosted: false,
    views: 60,
    commission: { percentage: 10, amount: 12000, status: "paid", paidAt: new Date("2024-05-01") },
  },
  {
    createdBy: IDS.agent,
    title: "Garden Villa in Uttara",
    description:
      "Spacious villa with a large private garden and modern amenities in a quiet Uttara neighborhood.",
    catagory: "House",
    type: "Rent",
    address: "House 8, Sector 7, Uttara",
    city: "Dhaka",
    state: "Dhaka Division",
    zipCode: "1230",
    country: "Bangladesh",
    location: {
      type: "Point",
      coordinates: [90.3995, 23.8759],
    },
    price: 65000,
    areaSqFt: 2800,
    yearBuilt: 2018,
    bedrooms: 4,
    bathrooms: 4,
    kitchen: 1,
    garage: 1,
    images: IMG.house2,
    status: "Pending",
    features: ["Garden", "Terrace"],
    amenities: ["Security", "Garden"],
    isFeatures: false,
    isBosted: false,
    views: 95,
    favorites: 12,
    commission: { percentage: 0, amount: 0, status: "waived" },
  },
];

const seedProperties = async () => {
  const result = await upsertByUnique(Property, "title", propertiesData);
  console.log(`Properties seeded (${result.created} created, ${result.updated} updated)`);
};

module.exports = { seedProperties };
